version: "3"
services:
  prisma:
    build: ../../prisma-engine/
    restart: always
    ports:
      - "4466:4466"
    volumes:
      - ../prisma-service:/etc/datamodel
    environment:
      PRISMA_DML_PATH: /etc/datamodel/datamodel_sql.prisma
  db:
    image: timms/postgres-logging:10.3
    container_name: psql
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
    ports:
      - "5432:5432"
volumes:
  postgres:
